/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PackageInfo {
  name: string
  version: string
  description: string
  keywords: Array<string>
  path: string
}
export declare function resolve(packageName: string): PackageInfo | null
